sudo: false
language: python
cache: pip
git:
  depth: 1

python:
  - "2.7"
  - "3.5"

env:
  - DJANGO="Django>=1.11,<2.0" 
  - DJANGO="Django>=2.0,<2.1"

matrix:
  exclude:
    - env: DJANGO="Django>=2.0,<2.1"
      python: "2.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install $DJANGO djangorestframework~=3.8.0 mock pytest pytest-django
# command to run tests, e.g. python setup.py test
script: cd tests ; pytest -v
